# Generated by Django 2.1.4 on 2018-12-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationapp', '0002_auto_20181208_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='projector',
            field=models.BooleanField(default=False, verbose_name='projektor'),
        ),
    ]
