# Generated by Django 2.1.4 on 2018-12-17 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservationapp', '0003_auto_20181208_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Rezerwacja', 'verbose_name_plural': 'Rezerwacje'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Sala', 'verbose_name_plural': 'Sale'},
        ),
    ]
