# Generated by Django 2.1.4 on 2018-12-17 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservationapp', '0004_auto_20181217_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservationapp.Room', verbose_name='Sala'),
        ),
    ]
